import type { Locale } from '../lib/site';
interface Engagement { title:string; trigger:string; decision:string; process:string; contribution:string; outputs:string; change:string; }
interface AdvisoryContent { title:string; lead:string; formats:string; labels:Record<'decision'|'process'|'contribution'|'outputs'|'change',string>; engagements:Engagement[]; artifactTitle:string; artifactLabel:string; artifact:{title:string;body:string}[]; proofTitle:string; proofLabel:string; proofContext:string; proofWork:string; proofOutput:string; }
export const advisory = {
pl: {
 title:'Od trudnej decyzji do warunków jej wykonania.',lead:'Możesz zaangażować mnie do rozpoznania problemu, zaprojektowania zmiany albo doradztwa podczas jej realizacji. Punktem wyjścia jest konkretna decyzja i osoby, które mają mandat ją podjąć.',formats:'Trzy sposoby pracy. Wybieramy potrzebny.',
 labels:{decision:'Co rozstrzygamy',process:'Jak pracujemy',contribution:'Co wnosi zespół',outputs:'Co zostaje',change:'Co staje się możliwe'},
 engagements:[
 {title:'Diagnoza decyzji',trigger:'Gdy zespół nie zgadza się, gdzie leży problem.',decision:'Co naprawdę blokuje postęp i czym warto zająć się najpierw?',process:'Prześledzimy konkretną decyzję przez priorytety, finansowanie, zależności i odpowiedzialność. Oddzielimy fakty od założeń.',contribution:'Sponsor, właściciele problemu oraz aktualne priorytety, ograniczenia i dostępne dowody.',outputs:'Mapa problemu i zależności, kryteria wyboru oraz lista decyzji z właścicielami i brakującymi informacjami.',change:'Wybór problemu i zakresu zmiany, zanim organizacja uruchomi kolejną inicjatywę.'},
 {title:'Projekt zmiany',trigger:'Gdy kierunek jest wybrany, ale organizacja nie jest gotowa go wykonać.',decision:'Co zmienić w odpowiedzialności, technologii i inwestycjach?',process:'Porównamy warianty i ich konsekwencje. Zaprojektujemy sposób podejmowania decyzji oraz przejście od obecnego działania do docelowego.',contribution:'Kryteria sukcesu, granice zmiany, właściciele obszarów i gotowość do rozstrzygnięcia kompromisów.',outputs:'Porównanie wariantów, podział uprawnień decyzyjnych, konsekwencje dla architektury i finansowania oraz plan przejścia.',change:'Zatwierdzenie spójnej zmiany wraz z odpowiedzialnością i warunkami jej przeglądu.'},
 {title:'Doradztwo w wykonaniu',trigger:'Gdy zmiana trwa, a nowe informacje podważają pierwotny plan.',decision:'Co kontynuować, zatrzymać, połączyć lub przełożyć?',process:'Przygotujemy decyzje do przeglądów, sprawdzimy założenia i zależności. Będę kwestionował plan tam, gdzie dowody przestają go wspierać.',contribution:'Aktualne dane z wykonania oraz osoby z mandatem do zmiany priorytetów, zakresu i finansowania.',outputs:'Zapis decyzji z uzasadnieniem, kolejność działań i warunki powrotu do wcześniejszych rozstrzygnięć.',change:'Korekta działania na podstawie dowodów, zanim utrzymywanie planu stanie się celem samym w sobie.'}
 ],
 artifactTitle:'Decyzja, którą da się przekazać dalej.',artifactLabel:'Przykładowy rezultat · karta decyzji, nie opis klienta',
 artifact:[{title:'Decyzja',body:'Czy uruchomić inicjatywę teraz, czy po uwolnieniu wspólnego zespołu?'},{title:'Warianty i koszt wyboru',body:'Start teraz: konkurencja o ludzi. Później: przesunięcie oczekiwanego efektu.'},{title:'Właściciel i dowody',body:'Osoba z mandatem do ustalenia priorytetu; dostępność zespołu i zależności wymagające potwierdzenia.'},{title:'Warunek powrotu',body:'Ponowny przegląd, gdy zmieni się dostępność zespołu lub znaczenie oczekiwanego efektu.'}],
 proofLabel:'Z praktyki · portfel inicjatyw',proofTitle:'Najpierw porównywalne wybory.',proofContext:'Nakładające się inicjatywy korzystały ze wspólnych zdolności i ograniczonej dostępności zespołów.',proofWork:'Analiza połączyła oczekiwane efekty, zależności, koszt alternatywny i architekturę docelową.',proofOutput:'Powstała podstawa do decyzji: zatrzymać, połączyć, ustalić kolejność lub kontynuować. Punktem odniesienia stał się cały portfel.'
},
en:{
 title:'From a difficult decision to the conditions for delivery.',lead:'Engage me to diagnose a problem, design a change or advise during execution. We start with a specific decision and the people who have the authority to make it.',formats:'Three ways to work. We choose the one needed.',
 labels:{decision:'The decision',process:'How we work',contribution:'Your team contributes',outputs:'What remains',change:'What becomes possible'},
 engagements:[
 {title:'Decision diagnostic',trigger:'When the team disagrees about where the problem lies.',decision:'What actually blocks progress, and what deserves attention first?',process:'We trace a concrete decision through priorities, funding, dependencies and accountability. We separate facts from assumptions.',contribution:'A sponsor, the relevant owners, current priorities, constraints and available evidence.',outputs:'A problem and dependency map, selection criteria and a decision list with owners and missing evidence.',change:'Choosing the problem and scope of change before starting another initiative.'},
 {title:'Operating design',trigger:'When the direction is chosen but the organization cannot yet deliver it.',decision:'What must change in accountability, technology and investment?',process:'We compare options and consequences, design decision rights and work out the transition from current to intended operations.',contribution:'Success criteria, boundaries, domain owners and a willingness to resolve trade-offs.',outputs:'An option comparison, decision rights, implications for architecture and funding, and a transition plan.',change:'Authorizing a coherent change with accountable owners and review conditions.'},
 {title:'Execution advisory',trigger:'When change is under way and new evidence challenges the original plan.',decision:'What should continue, stop, combine or move later?',process:'We prepare decisions for reviews and examine assumptions and dependencies. I challenge the plan where evidence no longer supports it.',contribution:'Current execution evidence and people with authority to change priorities, scope and funding.',outputs:'A decision record with rationale, action sequencing and conditions for revisiting earlier choices.',change:'Adjusting action on evidence before preserving the plan becomes an end in itself.'}
 ],
 artifactTitle:'A decision others can act on.',artifactLabel:'Illustrative output · decision brief, not a client case',
 artifact:[{title:'Decision',body:'Start the initiative now, or wait until the shared team is available?'},{title:'Options and trade-off',body:'Now: competition for people. Later: a delayed intended outcome.'},{title:'Owner and evidence',body:'The person authorized to set the priority; team availability and dependencies requiring confirmation.'},{title:'Revisit condition',body:'Review again if team availability or the importance of the intended outcome changes.'}],
 proofLabel:'From practice · initiative portfolio',proofTitle:'Make the choices comparable first.',proofContext:'Overlapping initiatives drew on shared capabilities and limited team capacity.',proofWork:'The analysis connected intended outcomes, dependencies, opportunity cost and target architecture.',proofOutput:'It established a basis for decisions to stop, combine, sequence or continue. The whole portfolio became the point of reference.'
}
} satisfies Record<Locale, AdvisoryContent>;
