export const contact = { pl: {
  title: 'Kontakt – Arkadiusz Kamrowski',
  description: 'Rozmowa o trudnej decyzji, projekcie zmiany lub wsparciu w wykonaniu. Doradztwo dla zarządów i CIO.',
  eyebrow: 'Kontakt / zacznijmy od problemu',
  headline: 'Jaką decyzję chcecie podjąć?',
  lead: 'Napisz kilka zdań o sytuacji i najważniejszym ograniczeniu. W rozmowie sprawdzimy, gdzie mogę pomóc.',
  contextEyebrow: 'Dobry punkt startu',
  contextTitle: 'Wystarczą trzy rzeczy.',
  fit: ['Kontekst – co dzieje się w organizacji i dlaczego temat jest ważny teraz.', 'Decyzja – co trzeba rozstrzygnąć, zmienić albo zaprojektować.', 'Ograniczenie – co utrudnia ruch: zależność, mandat, finansowanie, ryzyko lub czas.'],
  linkedin: 'Jeżeli wolisz krótszy kontakt, LinkedIn pozostaje najprostszą alternatywą.',
  formEyebrow: 'Wiadomość',
  formTitle: 'Opisz sytuację.',
  formBody: 'Nie potrzebuję pełnego briefu. Przeczytam wiadomość i odpowiem e-mailem: ustalimy, czy i od jakiej rozmowy warto zacząć. Poufne szczegóły zostawmy na później.',
  privacy: 'Dane z formularza są używane wyłącznie do odpowiedzi na wiadomość.',
}, en: {
  title: 'Contact – Arkadiusz Kamrowski',
  description: 'Discuss a difficult decision, design a change or get an independent view during execution. Advisory for boards and CIOs.',
  eyebrow: 'Contact / start with the problem',
  headline: 'What do you need to decide?',
  lead: 'Describe the situation and the main constraint in a few sentences. We can discuss where my contribution would be useful.',
  contextEyebrow: 'A good starting point',
  contextTitle: 'Three things are enough.',
  fit: ['Context – what is happening and why the topic matters now.', 'Decision – what needs to be resolved, changed or designed.', 'Constraint – what blocks movement: dependency, mandate, funding, risk or time.'],
  linkedin: 'If you prefer a shorter first contact, LinkedIn remains the simplest alternative.',
  formEyebrow: 'Message',
  formTitle: 'Describe the situation.',
  formBody: 'No polished brief needed. I will read your message and reply by email to agree whether and how to start a conversation. Save confidential details for later.',
  privacy: 'Form data is used only to respond to your message.',
}};
