import type { Locale } from '../lib/site';
interface MethodContent {title:string;lead:string;modelTitle:string;questions:{title:string;body:string}[];feedback:string;useTitle:string;uses:string[];boundaryLabel:string;boundary:string;sourceLabel:string;}
export const method = {
pl:{title:'Cztery pytania. Jedna spójna odpowiedź.',lead:'OAF — Organizational Architecture Framework — to mój model pracy z relacjami między strategią, organizacją, inwestycjami i wykonaniem. Sprawdza, czy odpowiedzi poszczególnych obszarów mogą działać razem.',modelTitle:'Każda odpowiedź zmienia warunki następnej.',questions:[{title:'Dokąd zmierzamy?',body:'Jaki efekt uzasadnia zmianę i z czego świadomie rezygnujemy?'},{title:'Jak musimy działać?',body:'Jakie zdolności, technologia i uprawnienia są potrzebne, żeby osiągnąć ten efekt?'},{title:'Co finansujemy najpierw?',body:'Które inicjatywy uruchamiamy przy rzeczywistych zależnościach i dostępności ludzi?'},{title:'Co mówi wykonanie?',body:'Jakie dowody potwierdzają kierunek, a jakie wymagają zmiany wcześniejszych decyzji?'}],feedback:'Dowody z wykonania wracają do pytania o kierunek. Przegląd ma prawo zmienić decyzję.',useTitle:'Kiedy ten model pomaga',uses:['Strategia i finansowanie wskazują różne priorytety.','Zmiana technologiczna wymaga innego podziału odpowiedzialności.','Decyzje rozsądne dla pojedynczych działów wzajemnie się blokują.'],boundaryLabel:'Granice modelu',boundary:'OAF jest syntezą służącą diagnozie i projektowaniu połączeń. Nie zastępuje specjalistycznej architektury, zarządzania portfelem ani wiedzy branżowej. Nie wymaga wdrożenia nowej metodyki w całej organizacji.',sourceLabel:'Podstawy intelektualne'},
en:{title:'Four questions. One coherent answer.',lead:'OAF — Organizational Architecture Framework — is my model for working with the relationships between strategy, organization, investment and execution. It tests whether answers from different functions can work together.',modelTitle:'Each answer changes the conditions for the next.',questions:[{title:'Where are we going?',body:'What outcome justifies change, and what do we deliberately give up?'},{title:'How must we operate?',body:'Which capabilities, technology and decision rights are needed to achieve that outcome?'},{title:'What do we fund first?',body:'Which initiatives do we start given real dependencies and available people?'},{title:'What does execution tell us?',body:'Which evidence supports the direction, and which calls for earlier decisions to change?'}],feedback:'Execution evidence returns to the question of direction. A review must be allowed to change a decision.',useTitle:'When the model helps',uses:['Strategy and funding point to different priorities.','Technology change requires a different distribution of accountability.','Decisions that make sense within departments block one another.'],boundaryLabel:'Model boundaries',boundary:'OAF is a synthesis for diagnosing and designing connections. It does not replace specialist architecture, portfolio management or industry expertise. It does not require a new methodology to be implemented throughout the organization.',sourceLabel:'Intellectual foundations'}
} satisfies Record<Locale, MethodContent>;
export const foundations = [
{label:'Jay Galbraith · Star Model',href:'https://jaygalbraith.com/services/star-model/'},
{label:'McKinsey · 7-S',href:'https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/enduring-ideas-the-7-s-framework'},
{label:'Burton & Obel · Organization design',href:'https://link.springer.com/article/10.1186/s41469-018-0029-2'},
{label:'Ross, Weill & Robertson · Enterprise Architecture as Strategy',href:'https://cisr.mit.edu/publication/enterprise-architecture-as-strategy'}
];
